### ISSUE TITLE
Multiple calls operating on the same build folder leak resources from isolated environment

### ISSUE THREAD

**Issue by ghost** [diegoferigo/cmake-build-extension#26]
Hello,

Ninja is currently the only generator supported by cmake-build-extension: https://github.com/diegoferigo/cmake-build-extension/blob/bb836e445b743ace473e1c9a5666cb69e88aa922/src/cmake_build_extension/build_extension.py#L78

Unfortunately it is not installed on all platform and a great benefit of CMake is to be agnostic of the final build tool that is used.

It would be nice to add a configuration option that select a different generator in replacement of Ninja (e.g. Make)

**Comment by diegoferigo** [comment]
Hi @remy-phelipot, sorry for the late reply, I missed this issue somehow. `ninja` is a dependency, and it should provide ootb the missing command. 

https://github.com/diegoferigo/cmake-build-extension/blob/bb836e445b743ace473e1c9a5666cb69e88aa922/setup.cfg#L50

Can you provide more info on your use case?
